### ISSUE TITLE
Some voxel models not working. (I think)

### ISSUE THREAD

**Issue by MeatGrinderGuy101** [NightFright2k19/duke3d_voxelpack#126]
So simply put the current voxels for the enemies are not showing. The only one that is working is the Turrets (the "//" was already removed for the monster.def). However, sentry drones and Pig Cop Tanks don't work. I used both ways of installing the mode. I thought it was a raze problem, so tried buildgdx and eduke and still didn't work. I see the models in the pictures you posted for the page, and see that there are files for them. Is it not finished or is there something wrong?

**Comment by Dzierzan** [comment]
```
/*
// Slimer Egg (675)
voxel "voxels/monsters/0558_slimeregg0.kvx" { tile 558 }
voxel "voxels/monsters/0675_slimeregg1.kvx" { tile 675 }
voxel "voxels/monsters/0676_slimeregg2.kvx" { tile 676 }
voxel "voxels/monsters/0677_slimeregg3.kvx" { tile 677 } 

// Sentry Drone (1880)
voxel "voxels/monsters/1880_sentrydrone.kvx" { tile0 1880 tile1 1886 }

// Pig Cop Tank (1975)
dummytilerange 1986 1988 66 71
dummytilerange 1992 1996 66 71
voxel "voxels/monsters/1975_tank_move1.kvx" { tile0 1975 tile1 1979 scale .94 }
voxel "voxels/monsters/1975_tank_move2.kvx" { tile0 1980 tile1 1984 scale .94 }
voxel "voxels/monsters/1975_tank_shoot1.kvx" { tile0 1985 tile1 1989 scale .94 }
voxel "voxels/monsters/1975_tank_shoot2.kvx" { tile0 1990 tile1 1994 scale .94 }
voxel "voxels/monsters/1975_tank_empty.kvx" { tile 1995 scale .94 }
voxel "voxels/monsters/1975_tank_wreck.kvx" { tile 1996 scale .94 }
*/

// Gun Turret (2350)
voxel "voxels/monsters/2350_turret1.kvx" { tile0 2350 tile1 2354 }
voxel "voxels/monsters/2355_turret2.kvx" { tile0 2355 tile1 2359 }
voxel "voxels/monsters/2360_turret3.kvx" { tile0 2360 tile1 2364 }

```

Notice that Slimer Egg, Sentry Drone and Pig Cop Tank are all commented out with "/* */". Just remove these and you should be good.

**Comment by NightFright2k19** [comment]
This is intentional. Since there are only these few voxels for monsters, it would look weird and inconsistent to have these voxelized while the rest is not. 

Once there are more entries or we have some convenient means to toggle certain voxels on demand, these remain unused.

If you must have these at all costs, by all means, remove the comment in the def file. You must also include pigtank.con in eduke.con, btw.

Since this isn't a bug - closing this now.

**Comment by MeatGrinderGuy101** [comment]
Huh!
Well reasonable. Thanks for the heads up, I wish you guys luck on your future projects.
