### ISSUE TITLE
Add ifmatch subtoken for voxels

### ISSUE THREAD

**Issue by fgsfds** [NightFright2k19/duke3d_voxelpack#128]
https://voidpoint.io/terminx/eduke32/-/issues/305

This will allow to enable voxels for Vaca/NW in eduke and will prevent voxels for the original sprites to replace addon's sprites.

For example, 

`voxel "voxels/pickups/0021_pistol.kvx" { ifmatch { size 36 20 crc32 0xAD28D280} tile 21 }`

will only replace original pistol, but not vaca's.

**Comment by fgsfds** [comment]
I made a version of BAFEd where you can just copy ifmatch token.

[BafEd.zip](https://github.com/user-attachments/files/15585699/BafEd.zip)

![image](https://github.com/NightFright2k19/duke3d_voxelpack/assets/4870330/6d82a22e-9dc5-4663-8bdb-1d79f0afaa48)

**Comment by NightFright2k19** [comment]
For some reason, my copy of jPortable (v8 update 411) won't open that .jar file. No problems with v2.20 from the BuildGDX website. Does the new version have any specific prerequisites?

**Comment by fgsfds** [comment]
@NightFright2k19 try this one

[BAFEd.zip](https://github.com/user-attachments/files/15598601/BAFEd.zip)

**Comment by NightFright2k19** [comment]
That one seems to work. Thanks!

**Comment by fgsfds** [comment]
Better ask Hendricks about this, but my guess is that it needs details of the first tile in a sequence.

**Comment by fgsfds** [comment]
Fixed missing space before }

[BAFEd.zip](https://github.com/user-attachments/files/15614132/BAFEd.zip)

Also, I know it's a lot of work, but it wouldn't hurt to put ifmatch to every voxel. This way it's guaranteed that tiles from mods that replace original tiles won't in turn get overwritten by wrong voxels.

**Comment by NightFright2k19** [comment]
I will get to it before compiling another release. First priority was to get the addon voxels working without conflicts. By now there are tons of props, so that one will keep me busy for a while.

**Comment by NightFright2k19** [comment]
All remaining voxels have been defined. It appears that tile0/tile1/etc definitions work if you just use the ifmatch value of the first tile. Tested with the camera in E1L1. It doesn't move around, though. However, I think it didn't do that before, either.
