### ISSUE TITLE
[Duke Caribbean] Coolbox and Radio voxels are levitating in midair.

### ISSUE THREAD

**Issue by Shockwave508** [NightFright2k19/duke3d_voxelpack#76]
In Duke Caribbean, the voxel objects known as...

3791_coolbox.kvx
3792_radio.kvx

are hovering in midair, likely due to incorrect Y-axis offsets.

Version of Raze used is v1.1.2 (through Raze Touch).

![Screenshot_2021-07-31-05-54-12-209_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/127737760-d3f73579-ef04-4cf8-b595-b0a2faa19531.jpg)
![Screenshot_2021-07-31-05-54-23-304_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/127737764-471a6d88-6f1d-48d3-a20f-6108a44c0725.jpg)

**Comment by NightFright2k19** [comment]
Raze bug.

**Comment by Dzierzan** [comment]
It's a Raze bug only? What was the fix for eduke32?
