### ISSUE TITLE
[Duke Caribbean] Pineapple "pipebombs" use vanilla Duke 3D voxels.

### ISSUE THREAD

**Issue by Shockwave508** [NightFright2k19/duke3d_voxelpack#77]
In Duke Caribbean, the throwable pineapple bombs do not have their own unique voxels, neither for the ammo pickup or thrown bomb, instead using the vanilla pipebomb voxels from Duke 3D.

![Screenshot_2021-07-31-06-01-45-730_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/127737886-6f15971f-36a0-40b0-b051-468f10fdcdbf.jpg)
![Screenshot_2021-07-31-06-01-41-824_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/127737892-dc9d52cf-7073-45de-978d-b45e6e00f894.jpg)

**Comment by NightFright2k19** [comment]
Not a bug. Voxel has not been made yet, Caribbean voxels are not complete.

**Comment by Dzierzan** [comment]
Well... I can make them now. Shouldn't be too hard to make.
